theme: jekyll-theme-minimal
title: 破万里浪
author:
  name: Haolei (Michael) Fang 
url: https://fanghaolei.github.io/
description: Sharing knowledge of data science and 
permalink: /:index.html
gems:
   - jekyll-mentions
   - jemoji
   - jekyll-redirect-from
   - jekyll-sitemap
   - jekyll-feed
   - jekyll-seo-tag